import 'package:on_chain/utils/utils/number_utils.dart';

/// Represents a log entry from a Conflux transaction.
/// 
/// Logs are generated by smart contract events and contain indexed and 
/// non-indexed data emitted during contract execution.
class CFXLog {
  /// The address of the contract that generated this log.
  final String address;

  /// Array of 0 to 4 indexed log arguments (topics).
  /// The first topic is typically the event signature hash.
  final List<String> topics;

  /// The non-indexed data that was emitted along with the event.
  final String data;

  /// The hash of the block containing this log.
  final String? blockHash;

  /// The epoch number of the block containing this log.
  final int? epochNumber;

  /// The hash of the transaction that generated this log.
  final String? transactionHash;

  /// The index of the transaction within the block.
  final int? transactionIndex;

  /// The index of this log within all logs in the block.
  final int? logIndex;

  /// The index of this log within the transaction.
  final int? transactionLogIndex;

  const CFXLog({
    required this.address,
    required this.topics,
    required this.data,
    this.blockHash,
    this.epochNumber,
    this.transactionHash,
    this.transactionIndex,
    this.logIndex,
    this.transactionLogIndex,
  });

  /// Creates a [CFXLog] from a JSON map.
  factory CFXLog.fromJson(Map<String, dynamic> json) {
    return CFXLog(
      address: json['address'],
      topics: (json['topics'] as List).cast<String>(),
      data: json['data'],
      blockHash: json['blockHash'],
      epochNumber: PluginIntUtils.tryHexToInt(json['epochNumber']),
      transactionHash: json['transactionHash'],
      transactionIndex: PluginIntUtils.tryHexToInt(json['transactionIndex']),
      logIndex: PluginIntUtils.tryHexToInt(json['logIndex']),
      transactionLogIndex: PluginIntUtils.tryHexToInt(json['transactionLogIndex']),
    );
  }

  /// Converts this log to a JSON map.
  Map<String, dynamic> toJson() {
    return {
      'address': address,
      'topics': topics,
      'data': data,
      if (blockHash != null) 'blockHash': blockHash,
      if (epochNumber != null) 'epochNumber': '0x${epochNumber!.toRadixString(16)}',
      if (transactionHash != null) 'transactionHash': transactionHash,
      if (transactionIndex != null) 'transactionIndex': '0x${transactionIndex!.toRadixString(16)}',
      if (logIndex != null) 'logIndex': '0x${logIndex!.toRadixString(16)}',
      if (transactionLogIndex != null) 'transactionLogIndex': '0x${transactionLogIndex!.toRadixString(16)}',
    };
  }

  @override
  String toString() {
    return 'CFXLog{address: $address, topics: $topics, data: $data, blockHash: $blockHash, epochNumber: $epochNumber}';
  }
}

